"use client";

import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Zap,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Store,
  ShoppingBag,
  Code2,
  GraduationCap,
} from "lucide-react";

const demos = [
  {
    slug: "demo-store",
    name: "Sol Brew Coffee",
    tagline: "Wake up to web3 ☕",
    description: "Premium specialty coffee — retail storefront with product catalog",
    icon: ShoppingBag,
    color: "#D97706",
    products: 3,
    category: "Retail / E-Commerce",
  },
  {
    slug: "web3-studio",
    name: "Nexus Web3 Studio",
    tagline: "Build different.",
    description: "Dev agency — services, audits, and strategy calls",
    icon: Code2,
    color: "#3B82F6",
    products: 3,
    category: "Services / Agency",
  },
  {
    slug: "crypto-academy",
    name: "Solana Academy",
    tagline: "From zero to Solana dev 🚀",
    description: "Online education — courses, workshops, and mentoring",
    icon: GraduationCap,
    color: "#14F195",
    products: 4,
    category: "Education / Digital",
  },
];

export default function ExplorePage() {
  return (
    <main className="min-h-screen">
      {/* Header */}
      <div className="border-b border-border/40 bg-background/60 backdrop-blur-xl sticky top-0 z-50">
        <div className="container mx-auto flex h-14 items-center justify-between px-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Paygent
          </Link>
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-solana-gradient">
              <Zap className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="text-sm font-semibold">Explore</span>
          </div>
          <Link href="/create">
            <Button variant="gradient" size="sm">
              Create Yours
            </Button>
          </Link>
        </div>
      </div>

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        {/* Hero */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <Badge className="mb-4 bg-solana-green/10 text-solana-green border-solana-green/20">
            <Store className="h-3 w-3 mr-1" />
            Live Examples
          </Badge>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            See what Paygent builds
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Every storefront below was generated by our AI agent in under 60 seconds.
            Click any to explore the live payment experience.
          </p>
        </motion.div>

        {/* Store cards */}
        <div className="space-y-6">
          {demos.map((demo, i) => {
            const Icon = demo.icon;
            return (
              <motion.div
                key={demo.slug}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
              >
                <Card className="overflow-hidden hover:border-white/10 transition-all group">
                  <CardContent className="p-0">
                    <div className="flex flex-col sm:flex-row">
                      {/* Icon section */}
                      <div
                        className="sm:w-48 p-6 flex items-center justify-center"
                        style={{ background: `${demo.color}08` }}
                      >
                        <div
                          className="h-20 w-20 rounded-2xl flex items-center justify-center"
                          style={{
                            background: `linear-gradient(135deg, ${demo.color}30, ${demo.color}10)`,
                            boxShadow: `0 4px 20px ${demo.color}15`,
                          }}
                        >
                          <Icon className="h-10 w-10" style={{ color: demo.color }} />
                        </div>
                      </div>

                      {/* Info */}
                      <div className="flex-1 p-6 flex flex-col justify-between">
                        <div>
                          <div className="flex items-start justify-between mb-1">
                            <div>
                              <h2 className="text-xl font-bold">{demo.name}</h2>
                              <p className="text-sm font-medium" style={{ color: demo.color }}>
                                {demo.tagline}
                              </p>
                            </div>
                            <Badge variant="outline" className="text-xs shrink-0 ml-3">
                              {demo.category}
                            </Badge>
                          </div>
                          <p className="text-muted-foreground mt-2 mb-4">
                            {demo.description}
                          </p>
                        </div>

                        <div className="flex items-center justify-between">
                          <span className="text-xs text-muted-foreground">
                            {demo.products} products • Live on devnet
                          </span>
                          <div className="flex gap-2">
                            <Link href={`/pay/${demo.slug}`}>
                              <Button variant="outline" size="sm" className="gap-1.5 text-xs group-hover:border-white/15">
                                View Store
                                <ExternalLink className="h-3 w-3" />
                              </Button>
                            </Link>
                            <Link href={`/dashboard/${demo.slug}`}>
                              <Button variant="ghost" size="sm" className="gap-1.5 text-xs">
                                Dashboard
                                <ArrowRight className="h-3 w-3" />
                              </Button>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="text-center mt-12 pt-8 border-t border-border/40"
        >
          <h2 className="text-2xl font-bold mb-3">Build your own in 60 seconds</h2>
          <p className="text-muted-foreground mb-6">
            Tell Paygent about your business. The AI handles the rest.
          </p>
          <Link href="/create">
            <Button variant="gradient" size="lg" className="gap-2">
              <Zap className="h-4 w-4" />
              Create Storefront
            </Button>
          </Link>
        </motion.div>
      </div>
    </main>
  );
}
